version: '3.9'
services:
  sql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=automation
    volumes:
      - /configs:/home/ubuntu
    restart: always
  